### ISSUE TITLE
Bug: `yakumo publish` 无法在 npm 账号启用双因素认证时使用

### ISSUE THREAD

**Issue by idranme** [shigma/yakumo#11]
当 npm 的 2FA 开为开启状态时，`yakumo publish` 无法发布包，且没有报错。

```
PS D:\develop\xxx> yarn pub
✔ Loading workspaces (4/4)
✔ All workspaces are up to date.
```

yakumo-publish: 0.3.4
yarn: 3.5.1

**Comment by shigma** [comment]
这个问题无法解决吧，npm 开了 2FA 本来就不允许 CI 发布。

**Comment by idranme** [comment]
> 这个问题无法解决吧，npm 开了 2FA 本来就不允许 CI 发布。

目前运行 `npm publish` 的时候，会启动浏览器进行验证。我们或许可以让用户手动打开链接验证，这样在 CI 的时候也能发布，虽然不太完美。在验证页面，有个选择可以让 5 分钟内的验证不需要再经过 2FA。

**Comment by shigma** [comment]
你说得对。那这个 issue 应该是可以通过代码解决的。

**Comment by shigma** [comment]
目前可以通过先 login 再 publish 的方式解决。亲测有效。

且如果失败后不会显示 up to date。
