### ISSUE TITLE
Feature: 在构建完成时, 输出一个提示

### ISSUE THREAD

**Issue by idranme** [shigma/yakumo#14]
`yakumo build`

**Comment by CyanChanges** [comment]
yakumo build 应该其实是按照 yakumo.yml 中的 pipeline 里的 build 来执行的？（
理论上来讲是不是可以写一个 yakumo（cordis） 插件来实现构建完成有提示，
然后把这个插件加到 build pipeline 的最后，这样就可以在最后输出提示了（
