### ISSUE TITLE
Feature: `yakumo upgrade`支持仅更新root package.json

### ISSUE THREAD

**Issue by Hieuzest** [shigma/yakumo#17]
此需求的场景有：
- 本地有clone的koishi/webui等upstream的场合
- 本地的开发中插件需要保持兼容性不希望被升级依赖的场合

此外：考虑和其他插件一样允许仅更新指定工作区，还是说这样做会导致什么问题？

**Comment by CyanChanges** [comment]
#15 ?

**Comment by Hieuzest** [comment]
我意识到这不是yakumo的适用范畴了，此issue可能是invalid。
这样看来对我而言更新bp的最佳实践应该是ncu，我不应该使用dep的。

**Comment by shigma** [comment]
Closed due to duplicate of #15.

Please see https://github.com/cordiverse/yakumo/issues/15#issuecomment-1963606074.
