### ISSUE TITLE
yakumo-version: keep current package.json indention

### ISSUE THREAD

**Issue by undefined-moe** [shigma/yakumo#2]
at https://github.com/shigma/yakumo/blob/master/packages/version/src/index.ts#L62 , indents are hard-coded to 2 spaces, while sometimes package.json is using 4 spaces for indention (or other cases?)

**Comment by shigma** [comment]
npm and yarn will create and maintain the package.json with 2-space indention, so it will lead to inconsistencies if you persist other indention styles.

**Comment by undefined-moe** [comment]
both `npm@6.14.16` and `yarn@3.0.2` is respecting current indent style.

**Comment by shigma** [comment]
but npm and yarn init are creating 2-space indented files.

**Comment by undefined-moe** [comment]
related: https://github.com/npm/npm/issues/5694

**Comment by shigma** [comment]
You got me right.
