### ISSUE TITLE
希望增加缓存清理功能

### ISSUE THREAD

**Issue by Somiona** [shigma/yakumo#5]
最近遇上了一个koishi升级到4.11后加载Scoped插件报错的问题，在和Koishi Dev群友讨论之后排查各种问题，发现是之前build的缓存引发了此问题。如果可以增加一个yakumo clean指令，用于清理
	<project_root>/plugin/<plugin_name>/lib
	<project_root>/plugin/<plugin_name>/tsconfig.tsbuildinfo
	<project_root>/node_modules/<plugin_name>
	<project_root>/node_modules/<plugin_scope>/<plugin_name>
并且在yakumo upgrade后自动执行的话
或许可以减少未来出现此类bug的可能

原报错信息
![G% SQ{7 M0~WS B)X%BC84C](https://user-images.githubusercontent.com/20739885/211183334-81b84d07-c1e3-426d-957e-cf199a528bf5.png)

**Comment by shigma** [comment]
不需要 clean，你只需要重新 yarn 重新 yarn build 即可。

**Comment by Somiona** [comment]
测试了一下，重新 yarn 重新 build 并不会清理掉
<project_root>/plugin/<plugin_name>/lib
<project_root>/plugin/<plugin_name>/tsconfig.tsbuildinfo
这两个文件，对于我遇上的问题需要把这两个删掉之后重新 yarn build 才解决了的

**Comment by shigma** [comment]
能更具体地说说你是怎么遇到这种情况的吗？我没有复现必须删掉 lib 和 tsbuildinfo 才能运行的情况。

**Comment by Somiona** [comment]
您好 我这边的情况是从4.10.6直接升级到4.11.1之后出现的这个问题，用的yakumo upgrade

**Comment by Seidko** [comment]
目前我打算做这个项目，我将其命名为 `yakumo clean`

据我观察，需要清理的项目应该包括 `outDir` 中的文件，`tsconfig.tsbuildinfo` 还有 `tsconfig.temp.json`

请问还有什么需要补充的吗？

**Comment by shigma** [comment]
`tsconfig.temp.json` 不需要删，因为每次都会重新生成，且不会影响 cache hit。

**Comment by Seidko** [comment]
不过我觉得删掉也好，符合 `clean` 的作用

**Comment by shigma** [comment]
并且这个功能与 build 耦合，所以可能不应该作为独立的指令，或许可以考虑 `yakumo build --clean`？

**Comment by shigma** [comment]
> 不过我觉得删掉也好，符合 `clean` 的作用

删掉也可，我都行。

**Comment by Seidko** [comment]
> 并且这个功能与 build 耦合，所以可能不应该作为独立的指令，或许可以考虑 `yakumo build --clean`？

感觉可以，到时候权衡一下成本一下要不要做好了

**Comment by Seidko** [comment]
想了想还是做成 `yakumo build --clean` 好了，开单独的 `clean` 似乎没有太大的必要

**Comment by Seidko** [comment]
`node_modules` 中的符号链接要管吗？还是说 `yarn` 或者 `npm` 会自动处理？

需不需要在 clean 完成以后 `yarn` 或 `npm i` 一下？

**Comment by shigma** [comment]
此 issue 与符号链接没有关系，只与 build 产物有关。
