### ISSUE TITLE
[Bug] publish path error in Windows

### ISSUE THREAD

**Issue by RF-Tar-Railt** [shigma/yakumo#8]
假设

```
workspace
├─── packages
│   ├─── foo
│   │   ├─── package.json
│   │   └─── ...
│   └─── ...
├─── package.json  // 写有 script pub: yakumo publish
└─── ...  
```

`yakumo publish` 实际生成的命令为 `npm publish packages/foo --tag latest --access public --color`

在windows下 `npm` 不会将其识别为路径而是 `git url`

导致其会运行命令 `git --no-replace-objects ls-remote ssh://git@github.com/packages/foo.git` 并引发报错

手动输入 `npm publish packages\foo --tag latest --access public --color` 后可以正常发布

（或许也可以给npm提一份？）

**Comment by shigma** [comment]
还有这种事，这也太怪了.jpg

**Comment by shigma** [comment]
> A package is interpreted the same way as other commands (like npm install and can be:
> a) a folder containing a program described by a [package.json](https://docs.npmjs.com/cli/v8/configuring-npm/package-json) file
> b) a gzipped tarball containing (a)
> c) a url that resolves to (b)
> d) a <name>@<version> that is published on the [registry](https://docs.npmjs.com/cli/v8/using-npm/registry) (see registry) with (c)
> e) a <name>@<tag> (see [npm dist-tag](https://docs.npmjs.com/cli/v8/commands/npm-dist-tag)) that points to (d)
> f) a <name> that has a "latest" tag satisfying (e)
> g) a <git remote url> that resolves to (a)

我感觉用 `/` 和 `\` 区分不太放心，你试试用绝对路径行不行？

**Comment by RF-Tar-Railt** [comment]
> > A package is interpreted the same way as other commands (like npm install and can be:
> 
> > a) a folder containing a program described by a [package.json](https://docs.npmjs.com/cli/v8/configuring-npm/package-json) file
> 
> > b) a gzipped tarball containing (a)
> 
> > c) a url that resolves to (b)
> 
> > d) a <name>@<version> that is published on the [registry](https://docs.npmjs.com/cli/v8/using-npm/registry) (see registry) with (c)
> 
> > e) a <name>@<tag> (see [npm dist-tag](https://docs.npmjs.com/cli/v8/commands/npm-dist-tag)) that points to (d)
> 
> > f) a <name> that has a "latest" tag satisfying (e)
> 
> > g) a <git remote url> that resolves to (a)
> 
> 
> 
> 我感觉用 `/` 和 `\` 区分不太放心，你试试用绝对路径行不行？

绝对路径下可行
