### ISSUE TITLE
[Bug] 不好复现的一个打包的bug

### ISSUE THREAD

**Issue by dingyi222666** [shigma/yakumo#9]
我在用yakumo打包写的项目的时候，发现打包后的产物被直接放在src目录里。

比如src文件夹有一个main.ts，运行一次yakumo build之后生成的产物(.js,.d.ts)全部都被放在src文件夹里了。。。
项目整体是参照类似[koishi-cache](https://github.com/koishijs/cache)这样的，tsconfig.json里的`outDir`是设置到lib文件夹的...

我是用的windows 11... 想问一下这该怎么解决。。。
（我在其他环境也试了一下没这个问题，好像就是在我自己主机的windows上有问题,所以才说不好复现）

**Comment by shigma** [comment]
应该仍然是你的配置有误。如果可以的话请提供源码仓库链接（是那个 chathub 吗？）

**Comment by dingyi222666** [comment]
> 应该仍然是你的配置有误。如果可以的话请提供源码仓库链接（是那个 chathub 吗？）

是的。

**Comment by dingyi222666** [comment]
问题好像解决了，确实是配置有误哈哈....
只要主项目的package.json
不要加
```json
"main": "index.js"
```
这样就可以了...

**Comment by shigma** [comment]
解决了就好~

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).
